### PR TITLE
Use the latest version of num-complex: v0.3

### PR DESCRIPTION
**Pull request by sebcrozet**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thanks! Could you please update it in all relevant crates? `blas`, `cblas`, `lapack`, and `lapacke` should do it. Please also add your name to the `authors` list in alphabetical order. Finally, we should probably bump up the minor version for all of them.

**Comment by termoshtt** [comment]
- blas: https://github.com/blas-lapack-rs/blas/pull/34
- cblas: https://github.com/blas-lapack-rs/cblas/pull/4
- lapacke: https://github.com/blas-lapack-rs/lapacke/pull/3

I create three PR to update num-complex to 0.3. I have no authority to merge them, please confirm them.

**Comment by IvanUkhov** [comment]
@termoshtt, I have added you to a team that has maintenance rights for those repositories. However, let us discuss the details in the pull requests.

**Comment by termoshtt** [comment]
Could you release 0.17.0?

**Comment by IvanUkhov** [comment]
Done! Also `blas`, `cblas`, and `lapacke`.

**Comment by termoshtt** [comment]
Thanks a lot!

**Pull request merged**
